function [pastureTIMESTAMP,pastureRecord,pasturePrecip,pastureUpper,pastureMid,pastureLower] = importPasture(filename, startRow, endRow)
%importPasture Import numeric data from a text file as column vectors.
%   [PASTURETIMESTAMP,PASTURERECORD,PASTUREPRECIP,PASTUREUPPER,PASTUREMID,PASTURELOWER]
%   = importPasture(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [PASTURETIMESTAMP,PASTURERECORD,PASTUREPRECIP,PASTUREUPPER,PASTUREMID,PASTURELOWER]
%   = importPasture(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [pastureTIMESTAMP,pastureRecord,pasturePrecip,pastureUpper,pastureMid,pastureLower] = importPasture('PrecipRunoff_Pasture_Combined.csv',5, 36884);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/23 00:22:08

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%f%f%f%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
pastureTIMESTAMP = dataArray{:, 1};
pastureRecord = dataArray{:, 2};
pasturePrecip = dataArray{:, 3};
pastureUpper = dataArray{:, 4};
pastureMid = dataArray{:, 5};
pastureLower = dataArray{:, 6};


