function [GC_Timestamp,GC_tips] = importGC(filename, startRow, endRow)
%Import Guabo Camp Import numeric data from a text file as column vectors.
%   [GC_TIMESTAMP,GC_TIPS] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [GC_TIMESTAMP,GC_TIPS] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [GC_Timestamp,GC_tips] = importfile('GuaboCampPrecip_5_12_16 to 8_10_16.csv',3, 2654);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/11/16 20:47:19

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format string for each line of text:
%   column2: datetimes (%{dd/MM/yy HH:mm}D)
%	column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*q%{dd/MM/yy HH:mm}D%f%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
GC_Timestamp = dataArray{:, 1};
GC_tips = dataArray{:, 2};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% GC_Timestamp=datenum(GC_Timestamp);


