function [ScanNo,Date,Time,Raw,CalibratedMM] = importLLData(filename, startRow, endRow)
%importLLData Import numeric data from a text file as column vectors.
%   [SCANNO,DATE,TIME,RAW,CALIBRATEDMM] = importLLData(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [SCANNO,DATE,TIME,RAW,CALIBRATEDMM] = importLLData(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [ScanNo,Date,Time,Raw,CalibratedMM] = importLLData('19L.CSV',7, 89);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/22 18:33:16

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 7;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: datetimes (%{HH:mm:ss}D)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%{HH:mm:ss}D%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ScanNo = dataArray{:, 1};
Date = dataArray{:, 2};
Time = dataArray{:, 3};
Raw = dataArray{:, 4};
CalibratedMM = dataArray{:, 5};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Time=datenum(Time);


