function [TimeStamp1,Precip_Totmm,RainfallRatemmhr] = importPASPrecip2(filename, startRow, endRow)
%importPASPrecip2 Import numeric data from a text file as column vectors.
%   [TIMESTAMP1,PRECIP_TOTMM,RAINFALLRATEMMHR] = importPASPrecip2(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [TIMESTAMP1,PRECIP_TOTMM,RAINFALLRATEMMHR] = importPASPrecip2(FILENAME,
%   STARTROW, ENDROW) Reads data from rows STARTROW through ENDROW of text
%   file FILENAME.
%
% Example:
%   [TimeStamp1,Precip_Totmm,RainfallRatemmhr] = importPASPrecip2('PAS_Precip_May22-July27_2016 - Sheet1.csv',2, 19153);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/29 20:03:05

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{"yyyy-MM-dd HH:mm:ss"}D)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{"yyyy-MM-dd HH:mm:ss"}D%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TimeStamp1 = dataArray{:, 1};
Precip_Totmm = dataArray{:, 2};
RainfallRatemmhr = dataArray{:, 3};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% TimeStamp1=datenum(TimeStamp1);


