function [llScan,llDate,llTime,llRaw,llMM,VarName6,llDateTime] = importLL30MinData(filename, startRow, endRow)
%importLL30MinData Import numeric data from a text file as column vectors.
%   [LLSCAN,LLDATE,LLTIME,LLRAW,LLMM,VARNAME6,LLDATETIME] =
%   importLL30MinData(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [LLSCAN,LLDATE,LLTIME,LLRAW,LLMM,VARNAME6,LLDATETIME] =
%   importLL30MinData(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [llScan,llDate,llTime,llRaw,llMM,VarName6,llDateTime] = importLL30MinData('LL30MinCal.CSV',10, 229);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/27 07:05:40

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 10;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: datetimes (%{HH:mm:ss}D)
%	column4: double (%f)
%   column5: double (%f)
%	column6: text (%s)
%   column7: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%{HH:mm:ss}D%f%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
llScan = dataArray{:, 1};
llDate = dataArray{:, 2};
llTime = dataArray{:, 3};
llRaw = dataArray{:, 4};
llMM = dataArray{:, 5};
VarName6 = dataArray{:, 6};
llDateTime = dataArray{:, 7};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% llTime=datenum(llTime);


